<?php

return array(
  'core.pkg.js' => array(
    'javelin-util',
    'javelin-install',
    'javelin-event',
    'javelin-stratcom',
    'javelin-behavior',
    'javelin-resource',
    'javelin-request',
    'javelin-vector',
    'javelin-dom',
    'javelin-json',
    'javelin-uri',
    'javelin-workflow',
    'javelin-mask',
    'javelin-typeahead',
    'javelin-typeahead-normalizer',
    'javelin-typeahead-source',
    'javelin-typeahead-preloaded-source',
    'javelin-typeahead-ondemand-source',
    'javelin-tokenizer',
    'javelin-history',
    'javelin-router',
    'javelin-routable',
    'javelin-behavior-aphront-basic-tokenizer',
    'javelin-behavior-workflow',
    'javelin-behavior-aphront-form-disable-on-submit',
    'phorge-keyboard-shortcut-manager',
    'phorge-keyboard-shortcut',
    'javelin-behavior-phorge-keyboard-shortcuts',
    'javelin-behavior-refresh-csrf',
    'javelin-behavior-phorge-watch-anchor',
    'javelin-behavior-phorge-autofocus',
    'phuix-dropdown-menu',
    'phuix-action-list-view',
    'phuix-action-view',
    'phuix-icon-view',
    'phorge-phtize',
    'javelin-behavior-phorge-oncopy',
    'phorge-tooltip',
    'javelin-behavior-phorge-tooltips',
    'phorge-prefab',
    'javelin-behavior-device',
    'javelin-behavior-toggle-class',
    'javelin-behavior-lightbox-attachments',
    'phorge-busy',
    'javelin-sound',
    'javelin-aphlict',
    'phorge-notification',
    'javelin-behavior-aphlict-listen',
    'javelin-behavior-phorge-search-typeahead',
    'javelin-behavior-aphlict-dropdown',
    'javelin-behavior-history-install',
    'javelin-behavior-phorge-gesture',
    'javelin-behavior-phorge-remarkup-assist',
    'phorge-textareautils',
    'phorge-file-upload',
    'javelin-behavior-global-drag-and-drop',
    'javelin-behavior-phorge-reveal-content',
    'phui-hovercard',
    'phui-hovercard-list',
    'javelin-behavior-phui-hovercards',
    'javelin-color',
    'javelin-fx',
    'phorge-draggable-list',
    'javelin-behavior-phorge-transaction-list',
    'javelin-behavior-phorge-show-older-transactions',
    'javelin-behavior-phui-dropdown-menu',
    'javelin-behavior-doorkeeper-tag',
    'phorge-title',
    'javelin-leader',
    'javelin-websocket',
    'javelin-behavior-dashboard-async-panel',
    'javelin-behavior-dashboard-tab-panel',
    'javelin-quicksand',
    'javelin-behavior-quicksand-blacklist',
    'javelin-behavior-high-security-warning',
    'javelin-behavior-read-only-warning',
    'javelin-scrollbar',
    'javelin-behavior-scrollbar',
    'javelin-behavior-durable-column',
    'conpherence-thread-manager',
    'javelin-behavior-detect-timezone',
    'javelin-behavior-setup-check-https',
    'javelin-behavior-aphlict-status',
    'javelin-behavior-user-menu',
    'phorge-favicon',
    'javelin-behavior-phui-tab-group',
    'javelin-behavior-phui-submenu',
    'phuix-button-view',
    'javelin-behavior-comment-actions',
    'phuix-form-control-view',
    'phuix-autocomplete',
  ),
  'core.pkg.css' => array(
    'phorge-core-css',
    'phorge-zindex-css',
    'phui-button-css',
    'phui-button-simple-css',
    'phui-theme-css',
    'phorge-standard-page-view',
    'aphront-dialog-view-css',
    'phui-form-view-css',
    'aphront-panel-view-css',
    'aphront-table-view-css',
    'aphront-tokenizer-control-css',
    'aphront-typeahead-control-css',
    'aphront-list-filter-view-css',
    'application-search-view-css',

    'phorge-remarkup-css',
    'syntax-highlighting-css',
    'syntax-default-css',
    'phui-pager-css',
    'aphront-tooltip-css',
    'phorge-flag-css',
    'phui-info-view-css',

    'phorge-main-menu-view',
    'phorge-notification-css',
    'phorge-notification-menu-css',
    'phui-lightbox-css',
    'phui-comment-panel-css',
    'phui-header-view-css',
    'phorge-nav-view-css',
    'phui-basic-nav-view-css',
    'phui-crumbs-view-css',
    'phui-oi-list-view-css',
    'phui-oi-color-css',
    'phui-oi-big-ui-css',
    'phui-oi-drag-ui-css',
    'phui-oi-simple-ui-css',
    'phui-oi-flush-ui-css',
    'global-drag-and-drop-css',
    'phui-spacing-css',
    'phui-form-css',
    'phui-icon-view-css',

    'phorge-action-list-view-css',
    'phui-property-list-view-css',
    'phui-tag-view-css',
    'phui-list-view-css',

    'font-fontawesome',
    'font-lato',
    'phui-font-icon-base-css',
    'phui-fontkit-css',
    'phui-box-css',
    'phui-object-box-css',
    'phui-timeline-view-css',
    'phui-two-column-view-css',
    'phui-curtain-view-css',

    'sprite-login-css',
    'sprite-tokens-css',
    'tokens-css',
    'auth-css',

    'phui-status-list-view-css',
    'phui-feed-story-css',
    'phorge-feed-css',
    'phorge-dashboard-css',
    'aphront-multi-column-view-css',
    'phui-curtain-object-ref-view-css',
    'phui-comment-form-css',
    'phui-head-thing-view-css',

    'conpherence-durable-column-view',
    'phui-button-bar-css',
  ),
  'conpherence.pkg.css' => array(
    'conpherence-menu-css',
    'conpherence-color-css',
    'conpherence-message-pane-css',
    'conpherence-notification-css',
    'conpherence-transaction-css',
    'conpherence-participant-pane-css',
    'conpherence-header-pane-css',
  ),
  'conpherence.pkg.js' => array(
    'javelin-behavior-conpherence-menu',
    'javelin-behavior-conpherence-participant-pane',
    'javelin-behavior-conpherence-pontificate',
    'javelin-behavior-toggle-widget',
  ),
  'differential.pkg.css' => array(
    'differential-core-view-css',
    'differential-changeset-view-css',
    'differential-revision-history-css',
    'differential-revision-list-css',
    'differential-table-of-contents-css',
    'differential-revision-comment-css',
    'differential-revision-add-comment-css',
    'phorge-object-selector-css',
    'phorge-content-source-view-css',
    'inline-comment-summary-css',
    'phui-inline-comment-view-css',
    'diff-tree-view-css',
    'phui-formation-view-css',
  ),
  'differential.pkg.js' => array(
    'phorge-drag-and-drop-file-upload',
    'phorge-shaped-request',

    'javelin-behavior-differential-populate',
    'javelin-behavior-differential-diff-radios',
    'javelin-behavior-aphront-drag-and-drop-textarea',
    'javelin-behavior-phorge-object-selector',
    'javelin-behavior-repository-crossreference',

    'javelin-behavior-aphront-more',

    'phorge-diff-inline-content-state',
    'phorge-diff-inline',
    'phorge-diff-changeset',
    'phorge-diff-changeset-list',
    'phorge-diff-tree-view',
    'phorge-diff-path-view',

    'phuix-formation-view',
    'phuix-formation-column-view',
    'phuix-formation-flank-view',

    'javelin-external-editor-link-engine',
  ),
  'diffusion.pkg.css' => array(
    'diffusion-icons-css',
  ),
  'diffusion.pkg.js' => array(
    'javelin-behavior-diffusion-pull-lastmodified',
    'javelin-behavior-diffusion-commit-graph',
    'javelin-behavior-audit-preview',
  ),
  'maniphest.pkg.css' => array(
    'maniphest-task-summary-css',
  ),
  'maniphest.pkg.js' => array(
    'javelin-behavior-maniphest-batch-selector',
    'javelin-behavior-maniphest-list-editor',
  ),
  'dark-console.pkg.js' => array(
    'javelin-behavior-dark-console',
    'phorge-darklog',
    'phorge-darkmessage',
  ),
);
