CREATE TABLE {$NAMESPACE}_xhpast.phpast_parsetree (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `authorPHID` VARBINARY(64) DEFAULT NULL,
  `input` LONGTEXT NOT NULL,
  `error` LONGTEXT DEFAULT NULL,
  `tokenStream` LONGBLOB NOT NULL,
  `tree` LONGTEXT NOT NULL,
  `dateCreated` INT UNSIGNED NOT NULL,
  `dateModified` INT UNSIGNED NOT NULL
);
