<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'missing-dependency.lint-test' => 'd9d7accf',
    'private-access.lint-test' => 'c5a55aba',
    'undocumented-install.lint-test' => 'b40b9df9',
    'uninstalled-documentation.lint-test' => 'a7b7fab0',
    'unknown-dependency.lint-test' => '70c6209f',
    'unnecessary-dependency.lint-test' => 'f7db3a25',
  ),
  'symbols' => array(
    'javelin-test-missing-dependency' => 'd9d7accf',
    'javelin-test-private-access' => 'c5a55aba',
    'javelin-test-undocumented-install' => 'b40b9df9',
    'javelin-test-uninstalled-documentation' => 'a7b7fab0',
    'javelin-test-unknown-dependency' => '70c6209f',
    'javelin-test-unnecessary-dependency' => 'f7db3a25',
  ),
  'requires' => array(
    '70c6209f' => array(
      'javelin-install',
      'javelin-does-not-exist',
    ),
    'a7b7fab0' => array(
      'javelin-install',
    ),
    'b40b9df9' => array(
      'javelin-install',
    ),
    'c5a55aba' => array(
      'javelin-install',
      'javelin-history',
    ),
    'd9d7accf' => array(
      'javelin-install',
    ),
    'f7db3a25' => array(
      'javelin-install',
      'javelin-workflow',
    ),
  ),
  'packages' => array(),
);
