<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'missing-dependency.lint-test' => '3f966f42',
    'private-access.lint-test' => 'fa831308',
    'undocumented-install.lint-test' => 'e575f333',
    'uninstalled-documentation.lint-test' => '9b61fd26',
    'unknown-dependency.lint-test' => 'abc533df',
    'unnecessary-dependency.lint-test' => '1608e0c1',
  ),
  'symbols' => array(
    'javelin-test' => 'e575f333',
  ),
  'requires' => array(
    '1608e0c1' => array(
      'javelin-install',
      'javelin-workflow',
    ),
    '3f966f42' => array(
      'javelin-install',
    ),
    '9b61fd26' => array(
      'javelin-install',
    ),
    'abc533df' => array(
      'javelin-install',
      'javelin-does-not-exist',
    ),
    'e575f333' => array(
      'javelin-install',
    ),
    'fa831308' => array(
      'javelin-install',
      'javelin-history',
    ),
  ),
  'packages' => array(),
);
